name: Version Bump
on:
  pull_request:
    types: [closed]

jobs:
  version-bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master  # or main, depending on your default branch

      - name: Get bump type
        id: bump
        run: |
          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'release: major') }} == 'true' ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ ${{ contains(github.event.pull_request.labels.*.name, 'release: minor') }} == 'true' ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ ${{ contains(github.event.pull_request.labels.*.name, 'release: patch') }} == 'true' ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "No version bump needed"
            exit 0
          fi

      - name: Setup Node
        if: steps.bump.outputs.type != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Bump version
        if: steps.bump.outputs.type != ''
        run: |
          npm version ${{ steps.bump.outputs.type }} -m "bump version: %s [skip ci]"

      - name: Push changes
        if: steps.bump.outputs.type != ''
        run: |
          git push
          git push --tags
